import type { Metadata } from 'next';

import { stratos } from '@/fonts';
import '@/styles/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className={`${stratos.className}`}>
      <body className='bg-page-bg relative flex min-h-screen w-screen flex-col overflow-x-hidden font-medium typo-text antialiased'>
        {children}
      </body>
    </html>
  );
}
